### ISSUE TITLE
logitech options

### ISSUE THREAD

**Issue by rossi2000** [smockle/homebridge-harmony-tv#13]
good evening

do all the options of hostinfo output work in the plugin?

so far i just added a few which seem to work, but some others dont work like 3D or Smart

"commands": [
                {
                    "action": "{\"command\":\"PowerOff\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "PowerOff",
                    "label": "PowerOff"
                },
                {
                    "action": "{\"command\":\"PowerOn\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "PowerOn",
                    "label": "PowerOn"
                },
                {
                    "action": "{\"command\":\"InputTv\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "InputTv",
                    "label": "InputTv"
                },
                {
                    "action": "{\"command\":\"InputHdmi1\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "InputHdmi1",
                    "label": "InputHdmi1"
                },
                {
                    "action": "{\"command\":\"InputHdmi2\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "InputHdmi2",
                    "label": "InputHdmi2"
                },
                {
                    "action": "{\"command\":\"InputHdmi3\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "InputHdmi3",
                    "label": "InputHdmi3"
                },
                {
                    "action": "{\"command\":\"3D\",\"type\":\"IRCommand\",\"deviceId\":\"xxxxxxxx\"}",
                    "name": "3D",
                    "label": "3D"
                }

also is it possible to get siri to action these? what are the commands

**Comment by smockle** [comment]
Hi @rossi2000, thanks for trying out the plugin! These are great questions.

> do all the options of hostinfo output work in the plugin?

It depends on what you mean by “work”. None of the output of `hubinfo.js` should _break_ the plugin, but some of it may not be supported by a. the plugin or b. HomeKit itself (yet).

> some others dont work like 3D or Smart

I don’t own a 3D TV, so I can’t test this personally. Does your TV treat 3D like a separate input?

If so, you can make `homebridge-harmony-tv-smockle` treat it like an input by replacing

```JSON
{
  "action": "{"command":"3D","type":"IRCommand","deviceId":"xxxxxxxx"}",
  "name": "3D",
  "label": "3D"
}
```

with

```JSON
{
  "action": "{"command":"3D","type":"IRCommand","deviceId":"xxxxxxxx"}",
  "name": "Input3D",
  "label": "Input3D"
}
```

If your TV treats 3D as a toggleable feature that applies to all inputs, AFAIK that’s not supported by [HAP-NodeJS](https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes-Television.js) or HomeKit itself.

> is it possible to get siri to action these

According to [this 9to5mac article](https://9to5mac.com/2019/01/31/homekit-tv-home-app-ios-12-2/), the answer is currently no:

> Siri control for switching inputs outside of scenes is missing for now, but it seems like a feature we could easily see in the future. For now, Siri is limited to turning TVs on and off and activating pre-configured scenes that include HomeKit TVs.

**Comment by rossi2000** [comment]
Hi mate

I added input to 3D then it showed in the HomeKit app but it didn’t do anything.
