### ISSUE TITLE
Hello, Thanks for this plugin 

### ISSUE THREAD

**Issue by CMaxim77** [smockle/homebridge-harmony-tv#15]
![image](https://user-images.githubusercontent.com/34638986/53698496-8addbb80-3dab-11e9-98cc-8853f494b0ba.png)

Im just starting out on Homebridge, it has been awhile since I have used it. (currently running HomeAssistant) I decided to purchase a new pi just for your plugin. im getting this error, do you know why?

**Comment by smockle** [comment]
@CMaxim77 Thanks for trying it out! I know exactly what is causing that error: Yesterday, I replaced one of the packages this plugin depends on (details: #11, #14), but I forgot to update the `scripts/hubinfo.js` file. 🤦‍♂️ I’m very sorry for the inconvenience, and I’ll work to resolve that right away.

**Comment by CMaxim77** [comment]
no inconvenience man! I appreciate your work and im glad its not something I did lol.

ill patiently wait for a fix :)

**Comment by smockle** [comment]
This should be fixed as of version`2.0.13`, which is published.

@CMaxim77 If you update (e.g. using `npm install -g homebridge-harmony-tv-smockle@2.0.13`), the command you were attempting to run before should work now. Thanks very much for your patience, and for taking the time to report this in the first place.
