### ISSUE TITLE
Plugin not installing: Permission denied

### ISSUE THREAD

**Issue by GreaterHater** [smockle/homebridge-harmony-tv#17]
Hi smockle,

I get this error on trying to install your plugin:

`xxx@xxxxx:~$ sudo npm install -g homebridge-harmony-tv-smockle`
`> curve25519-n@1.4.0 install /usr/lib/node_modules/homebridge-harmony-tv-smockle/node_modules/curve25519-n`
`> node-gyp rebuild`

`gyp ERR! configure error `
`gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/homebridge-harmony-tv-smockle/node_modules/curve25519-n/build'`
`gyp ERR! System Linux 4.4.0-145-generic`
`gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`
`gyp ERR! cwd /usr/lib/node_modules/homebridge-harmony-tv-smockle/node_modules/curve25519-n`
`gyp ERR! node -v v9.11.2`
`gyp ERR! node-gyp -v v3.8.0`
`gyp ERR! not ok `
`npm ERR! code ELIFECYCLE`
`npm ERR! errno 1`
`npm ERR! curve25519-n@1.4.0 install: 'node-gyp rebuild'`
`npm ERR! Exit status 1`

Any ideas what is wrong?
Thank you!
Stefan

**Node.js version:**
v9.11.2
**Plugin version:**
2.0.4

[2019-04-15T10_18_14_988Z-debug.log](https://github.com/smockle/homebridge-harmony-tv/files/3079739/2019-04-15T10_18_14_988Z-debug.log)

**Comment by GreaterHater** [comment]
Found it! On my machine (Ubuntu 16.04) the plugin has to be installed using the --unsafe-perm flag, i.e.
`sudo npm install -g --unsafe-perm  homebridge-harmony-tv-smockle`

Sorry for bothering
Stefan

**Comment by smockle** [comment]
I’m glad you found a solution! Thanks for reporting this and for sharing the fix. This will help other folks with the same error. Cheers!
