### ISSUE TITLE
Config.json incorrect?

### ISSUE THREAD

**Issue by misanthrophy** [smockle/homebridge-harmony-tv#9]
Hi, in your confif.json example you say: "accessory": "HarmonyTV",
But in the description below you say: "platform" must be "HarmonyTV"

What is the correct one?

**Comment by smockle** [comment]
> in the description below you say: "platform" must be "HarmonyTV"

It should be `"accessory"` not `"platform"`. I’ve updated the README. Thank you for noting this @misanthrophy!

> it failed for me at first until I removed the last "," (comma) on the "deviceId" line

Another good note, I’ve corrected this too. Thanks @sastafa!

**Comment by smockle** [comment]
Also—while I definitely appreciate the early feedback, please be aware that this plugin does not have any features yet.

If the plugin is configured correctly (and with your help the instructions in the README are improving), a TV accessory with three inputs should appear in the Apple Home app on iOS 12.2. But the HomeKit accessory added by this plugin is not yet connected to Harmony Hub/Remote actions.
